# Metadata for this documentation project.
# See https://quarto.orgcontent/reference/projects/websites.html
project:
    type: website
    output-dir: _site
format:
    html:
        toc: true
        toc-expand: true
        code-copy: true
        code-overflow: scroll
        grid:
            sidebar-width: 250px
            body-width: 800px
            margin-width: 250px
            gutter-width: 1.5em
        theme:
            - cosmo
            - assets/css/theme.scss
website:
    title: "xoshiro/xoroshiro PRNG's"
    image: "assets/images/logo.png"
    favicon: "assets/images/logo.png"
    open-graph: true
    twitter-card: true
    google-analytics: G-XV29LHZDKD
    site-url: "https://nessan.github.io/xoshiro"
    repo-url: "https://github.com/nessan/xoshiro"
    repo-subdir: docs
    issue-url: "https://github.com/nessan/xoshiro/issues/new/choose"
    repo-actions: [edit, issue]
    page-navigation: true
    bread-crumbs: false
    back-to-top-navigation: true
    page-footer:
        left: |
            Copyright (c) Nessan Fitzmaurice
        center: |
            Project is under the MIT License
        right:
            - icon: github
              href: "https://github.com/nessan/xoshiro"
              aria-label: GitHub Repo
            - icon: twitter
              href: https://twitter.com/nezzan
              aria-label: Twitter

    navbar:
        background: dark
        logo: "assets/images/logo.png"
        logo-alt: "The xoshiro library logo"
        title: RNG
        search: true
        pinned: true
        collapse-below: lg
        left:
            - text: "Home"
              file: index.qmd
            - text: "Generators"
              file: pages/generator.qmd
            - text: "States"
              file: pages/State.qmd
            - text: "Scramblers"
              file: pages/Scrambler.qmd
            - text: "Aliases"
              file: pages/type-aliases.qmd
            - text: "Partitions"
              file: pages/partition.qmd
            - text: "Jumps"
              file: pages/jump-technique.qmd
            - text: "More"
              menu:
                  - text: "Project Repo"
                    icon: "github"
                    href: "https://github.com/nessan/xoshiro"
                  - text: "Report a Bug"
                    icon: "bug"
                    href: "https://github.com/nessan/xoshiro/issues"
                  - text: "Ask a Question"
                    icon: "chat-right-text"
                    href: "https://github.com/nessan/xoshiro/discussions"
        tools:
            - icon: github
              href: "https://github.com/nessan/xoshiro"
              text: GitHub repo
            - icon: twitter
              href: https://twitter.com/nezzan
              aria-label: Twitter
    sidebar:
        style: floating
        type: light
        background: light
        align: left
        collapse-level: 2
        contents:
            - text: Overview
              href: index.qmd
            - text: "---"
            - section: "Generators"
              contents:
                  - text: "Introduction"
                    href: pages/generator.qmd
                  - text: "Declaration"
                    href: pages/generator.qmd#declaration
                  - text: "Class Types & Methods"
                    href: pages/generator.qmd#class-types-and-methods
                  - text: "Instance Methods"
                    href: pages/generator.qmd#instance-methods
                  - text: "Non-member Functions"
                    href: pages/generator.qmd#non-member-functions
                  - text: "Recommended Generators"
                    href: pages/type-aliases.qmd
            - text: "---"
            - section: "States"
              contents:
                  - text: "Introduction"
                    href: pages/State.qmd
                  - text: "Defined States"
                    href: pages/State.qmd#our-state-classes
                  - text: "Class Types & Methods"
                    href: pages/State.qmd#class-types-and-methods
                  - text: "Instance Methods"
                    href: pages/State.qmd#instance-methods
                  - text: "Precomputed Characteristics"
                    href: pages/State.qmd#precomputed-characteristics
            - text: "---"
            - section: "Scramblers"
              contents:
                  - text: "Introduction"
                    href: pages/Scrambler.qmd
                  - text: "Defined Scramblers"
                    href: pages/Scrambler.qmd#our-scrambler-classes
                  - text: "Methods"
                    href: pages/Scrambler.qmd#methods
            - text: "---"
            - section: "Stream Partitioning"
              contents:
                  - text: "Introduction"
                    href: pages/partition.qmd
                  - text: "Declaration"
                    href: pages/partition.qmd#declaration
                  - text: "Instance Methods"
                    href: pages/partition.qmd#instance-methods
            - text: "---"
            - section: "Technical Notes"
              contents:
                  - text: "The Jump Technique"
                    href: pages/jump-technique.qmd
editor:
    markdown:
        canonical: true
